/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model;

import com.quizzes.api.common.model.tables.Collection;
import com.quizzes.api.common.model.tables.CollectionOnAir;
import com.quizzes.api.common.model.tables.ContextProfile;
import com.quizzes.api.common.model.tables.ContextProfileEvent;
import com.quizzes.api.common.model.tables.Event;
import com.quizzes.api.common.model.tables.EventIndex;
import com.quizzes.api.common.model.tables.Group;
import com.quizzes.api.common.model.tables.GroupProfile;
import com.quizzes.api.common.model.tables.Profile;
import com.quizzes.api.common.model.tables.Resource;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 82642439;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			Collection.COLLECTION,
			CollectionOnAir.COLLECTION_ON_AIR,
			com.quizzes.api.common.model.tables.Context.CONTEXT,
			ContextProfile.CONTEXT_PROFILE,
			ContextProfileEvent.CONTEXT_PROFILE_EVENT,
			Event.EVENT,
			EventIndex.EVENT_INDEX,
			Group.GROUP,
			GroupProfile.GROUP_PROFILE,
			Profile.PROFILE,
			Resource.RESOURCE);
	}
}
