/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.collection
	 */
	public static final com.quizzes.api.common.tables.Collection COLLECTION = com.quizzes.api.common.tables.Collection.COLLECTION;

	/**
	 * The table public.collection_on_air
	 */
	public static final com.quizzes.api.common.tables.CollectionOnAir COLLECTION_ON_AIR = com.quizzes.api.common.tables.CollectionOnAir.COLLECTION_ON_AIR;

	/**
	 * The table public.context
	 */
	public static final com.quizzes.api.common.tables.Context CONTEXT = com.quizzes.api.common.tables.Context.CONTEXT;

	/**
	 * The table public.event
	 */
	public static final com.quizzes.api.common.tables.Event EVENT = com.quizzes.api.common.tables.Event.EVENT;

	/**
	 * The table public.event_index
	 */
	public static final com.quizzes.api.common.tables.EventIndex EVENT_INDEX = com.quizzes.api.common.tables.EventIndex.EVENT_INDEX;

	/**
	 * The table public.profile
	 */
	public static final com.quizzes.api.common.tables.Profile PROFILE = com.quizzes.api.common.tables.Profile.PROFILE;

	/**
	 * The table public.resource
	 */
	public static final com.quizzes.api.common.tables.Resource RESOURCE = com.quizzes.api.common.tables.Resource.RESOURCE;
}
