/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextProfileRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.core.model.jooq.tables.records.ContextProfileRecord> implements org.jooq.Record9<java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.lang.Boolean, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1045079023;

	/**
	 * Setter for <code>public.context_profile.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.context_profile.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.context_profile.context_id</code>.
	 */
	public void setContextId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.context_profile.context_id</code>.
	 */
	public java.util.UUID getContextId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.context_profile.profile_id</code>.
	 */
	public void setProfileId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.context_profile.profile_id</code>.
	 */
	public java.util.UUID getProfileId() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>public.context_profile.current_resource_id</code>.
	 */
	public void setCurrentResourceId(java.util.UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.context_profile.current_resource_id</code>.
	 */
	public java.util.UUID getCurrentResourceId() {
		return (java.util.UUID) getValue(3);
	}

	/**
	 * Setter for <code>public.context_profile.is_complete</code>.
	 */
	public void setIsComplete(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.context_profile.is_complete</code>.
	 */
	public java.lang.Boolean getIsComplete() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.context_profile.event_summary_data</code>.
	 */
	public void setEventSummaryData(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.context_profile.event_summary_data</code>.
	 */
	public java.lang.String getEventSummaryData() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.context_profile.taxonomy_sumary_data</code>.
	 */
	public void setTaxonomySumaryData(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.context_profile.taxonomy_sumary_data</code>.
	 */
	public java.lang.String getTaxonomySumaryData() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.context_profile.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.context_profile.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>public.context_profile.updated_at</code>.
	 */
	public void setUpdatedAt(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.context_profile.updated_at</code>.
	 */
	public java.sql.Timestamp getUpdatedAt() {
		return (java.sql.Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.lang.Boolean, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.lang.Boolean, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.CONTEXT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field4() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.CURRENT_RESOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.IS_COMPLETE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.EVENT_SUMMARY_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.TAXONOMY_SUMARY_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getContextId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value4() {
		return getCurrentResourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getIsComplete();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getEventSummaryData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getTaxonomySumaryData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value2(java.util.UUID value) {
		setContextId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value3(java.util.UUID value) {
		setProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value4(java.util.UUID value) {
		setCurrentResourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value5(java.lang.Boolean value) {
		setIsComplete(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value6(java.lang.String value) {
		setEventSummaryData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value7(java.lang.String value) {
		setTaxonomySumaryData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value8(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord value9(java.sql.Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfileRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.util.UUID value4, java.lang.Boolean value5, java.lang.String value6, java.lang.String value7, java.sql.Timestamp value8, java.sql.Timestamp value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContextProfileRecord
	 */
	public ContextProfileRecord() {
		super(com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE);
	}

	/**
	 * Create a detached, initialised ContextProfileRecord
	 */
	public ContextProfileRecord(java.util.UUID id, java.util.UUID contextId, java.util.UUID profileId, java.util.UUID currentResourceId, java.lang.Boolean isComplete, java.lang.String eventSummaryData, java.lang.String taxonomySumaryData, java.sql.Timestamp createdAt, java.sql.Timestamp updatedAt) {
		super(com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE);

		setValue(0, id);
		setValue(1, contextId);
		setValue(2, profileId);
		setValue(3, currentResourceId);
		setValue(4, isComplete);
		setValue(5, eventSummaryData);
		setValue(6, taxonomySumaryData);
		setValue(7, createdAt);
		setValue(8, updatedAt);
	}
}
