/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrentContextProfileRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.core.model.jooq.tables.records.CurrentContextProfileRecord> implements org.jooq.Record4<java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp> {

	private static final long serialVersionUID = -1660606041;

	/**
	 * Setter for <code>public.current_context_profile.context_id</code>.
	 */
	public void setContextId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.current_context_profile.context_id</code>.
	 */
	public java.util.UUID getContextId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.current_context_profile.profile_id</code>.
	 */
	public void setProfileId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.current_context_profile.profile_id</code>.
	 */
	public java.util.UUID getProfileId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.current_context_profile.context_profile_id</code>.
	 */
	public void setContextProfileId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.current_context_profile.context_profile_id</code>.
	 */
	public java.util.UUID getContextProfileId() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>public.current_context_profile.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.current_context_profile.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.core.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE.CONTEXT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.quizzes.api.core.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE.PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.quizzes.api.core.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE.CONTEXT_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.quizzes.api.core.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getContextId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getContextProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord value1(java.util.UUID value) {
		setContextId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord value2(java.util.UUID value) {
		setProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord value3(java.util.UUID value) {
		setContextProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord value4(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.sql.Timestamp value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CurrentContextProfileRecord
	 */
	public CurrentContextProfileRecord() {
		super(com.quizzes.api.core.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE);
	}

	/**
	 * Create a detached, initialised CurrentContextProfileRecord
	 */
	public CurrentContextProfileRecord(java.util.UUID contextId, java.util.UUID profileId, java.util.UUID contextProfileId, java.sql.Timestamp createdAt) {
		super(com.quizzes.api.core.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE);

		setValue(0, contextId);
		setValue(1, profileId);
		setValue(2, contextProfileId);
		setValue(3, createdAt);
	}
}
