/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.core.model.jooq.tables.records.SessionRecord> implements org.jooq.Record4<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -479151411;

	/**
	 * Setter for <code>public.session.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.session.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.session.profile_id</code>.
	 */
	public void setProfileId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.session.profile_id</code>.
	 */
	public java.util.UUID getProfileId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.session.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.session.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>public.session.last_access_at</code>.
	 */
	public void setLastAccessAt(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.session.last_access_at</code>.
	 */
	public java.sql.Timestamp getLastAccessAt() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.core.model.jooq.tables.Session.SESSION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.quizzes.api.core.model.jooq.tables.Session.SESSION.PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.quizzes.api.core.model.jooq.tables.Session.SESSION.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.quizzes.api.core.model.jooq.tables.Session.SESSION.LAST_ACCESS_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getLastAccessAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value2(java.util.UUID value) {
		setProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value3(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value4(java.sql.Timestamp value) {
		setLastAccessAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord values(java.util.UUID value1, java.util.UUID value2, java.sql.Timestamp value3, java.sql.Timestamp value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SessionRecord
	 */
	public SessionRecord() {
		super(com.quizzes.api.core.model.jooq.tables.Session.SESSION);
	}

	/**
	 * Create a detached, initialised SessionRecord
	 */
	public SessionRecord(java.util.UUID id, java.util.UUID profileId, java.sql.Timestamp createdAt, java.sql.Timestamp lastAccessAt) {
		super(com.quizzes.api.core.model.jooq.tables.Session.SESSION);

		setValue(0, id);
		setValue(1, profileId);
		setValue(2, createdAt);
		setValue(3, lastAccessAt);
	}
}
