version: '2'
services:
  web:
    image: openjdk:8-alpine
    command: /app/docker-run
    volumes:
      - .:/app
    depends_on:
      - postgres
      - activemq
      - memcached
  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quizzes
  activemq:
    image: edify-dkr.jfrog.io/activemq:5.13.3
  memcached:
    image: memcached:1.4-alpine

