/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.client
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Client CLIENT = com.quizzes.api.common.model.jooq.tables.Client.CLIENT;

	/**
	 * The table public.collection
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Collection COLLECTION = com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION;

	/**
	 * The table public.context
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Context CONTEXT = com.quizzes.api.common.model.jooq.tables.Context.CONTEXT;

	/**
	 * The table public.context_profile
	 */
	public static final com.quizzes.api.common.model.jooq.tables.ContextProfile CONTEXT_PROFILE = com.quizzes.api.common.model.jooq.tables.ContextProfile.CONTEXT_PROFILE;

	/**
	 * The table public.context_profile_event
	 */
	public static final com.quizzes.api.common.model.jooq.tables.ContextProfileEvent CONTEXT_PROFILE_EVENT = com.quizzes.api.common.model.jooq.tables.ContextProfileEvent.CONTEXT_PROFILE_EVENT;

	/**
	 * The table public.current_context_profile
	 */
	public static final com.quizzes.api.common.model.jooq.tables.CurrentContextProfile CURRENT_CONTEXT_PROFILE = com.quizzes.api.common.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE;

	/**
	 * The table public.group
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Group GROUP = com.quizzes.api.common.model.jooq.tables.Group.GROUP;

	/**
	 * The table public.group_profile
	 */
	public static final com.quizzes.api.common.model.jooq.tables.GroupProfile GROUP_PROFILE = com.quizzes.api.common.model.jooq.tables.GroupProfile.GROUP_PROFILE;

	/**
	 * The table public.profile
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Profile PROFILE = com.quizzes.api.common.model.jooq.tables.Profile.PROFILE;

	/**
	 * The table public.resource
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Resource RESOURCE = com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE;

	/**
	 * The table public.session
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Session SESSION = com.quizzes.api.common.model.jooq.tables.Session.SESSION;
}
