/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.collection
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Collection COLLECTION = com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION;

	/**
	 * The table public.collection_on_air
	 */
	public static final com.quizzes.api.common.model.jooq.tables.CollectionOnAir COLLECTION_ON_AIR = com.quizzes.api.common.model.jooq.tables.CollectionOnAir.COLLECTION_ON_AIR;

	/**
	 * The table public.context
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Context CONTEXT = com.quizzes.api.common.model.jooq.tables.Context.CONTEXT;

	/**
	 * The table public.context_profile
	 */
	public static final com.quizzes.api.common.model.jooq.tables.ContextProfile CONTEXT_PROFILE = com.quizzes.api.common.model.jooq.tables.ContextProfile.CONTEXT_PROFILE;

	/**
	 * The table public.context_profile_event
	 */
	public static final com.quizzes.api.common.model.jooq.tables.ContextProfileEvent CONTEXT_PROFILE_EVENT = com.quizzes.api.common.model.jooq.tables.ContextProfileEvent.CONTEXT_PROFILE_EVENT;

	/**
	 * The table public.event
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Event EVENT = com.quizzes.api.common.model.jooq.tables.Event.EVENT;

	/**
	 * The table public.event_index
	 */
	public static final com.quizzes.api.common.model.jooq.tables.EventIndex EVENT_INDEX = com.quizzes.api.common.model.jooq.tables.EventIndex.EVENT_INDEX;

	/**
	 * The table public.group
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Group GROUP = com.quizzes.api.common.model.jooq.tables.Group.GROUP;

	/**
	 * The table public.group_profile
	 */
	public static final com.quizzes.api.common.model.jooq.tables.GroupProfile GROUP_PROFILE = com.quizzes.api.common.model.jooq.tables.GroupProfile.GROUP_PROFILE;

	/**
	 * The table public.profile
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Profile PROFILE = com.quizzes.api.common.model.jooq.tables.Profile.PROFILE;

	/**
	 * The table public.resource
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Resource RESOURCE = com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE;
}
