/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.routines;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UuidNsUrl extends org.jooq.impl.AbstractRoutine<java.util.UUID> {

	private static final long serialVersionUID = 1986790060;

	/**
	 * The parameter <code>public.uuid_ns_url.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.UUID);

	/**
	 * Create a new routine call instance
	 */
	public UuidNsUrl() {
		super("uuid_ns_url", com.quizzes.api.common.model.Public.PUBLIC, org.jooq.impl.SQLDataType.UUID);

		setReturnParameter(RETURN_VALUE);
	}
}
