/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.routines;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UuidGenerateV5 extends org.jooq.impl.AbstractRoutine<java.util.UUID> {

	private static final long serialVersionUID = -1509237807;

	/**
	 * The parameter <code>public.uuid_generate_v5.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.UUID);

	/**
	 * The parameter <code>public.uuid_generate_v5.namespace</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> NAMESPACE = createParameter("namespace", org.jooq.impl.SQLDataType.UUID);

	/**
	 * The parameter <code>public.uuid_generate_v5.name</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> NAME = createParameter("name", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * Create a new routine call instance
	 */
	public UuidGenerateV5() {
		super("uuid_generate_v5", com.quizzes.api.common.model.Public.PUBLIC, org.jooq.impl.SQLDataType.UUID);

		setReturnParameter(RETURN_VALUE);
		addInParameter(NAMESPACE);
		addInParameter(NAME);
	}

	/**
	 * Set the <code>namespace</code> parameter IN value to the routine
	 */
	public void setNamespace(java.util.UUID value) {
		setValue(com.quizzes.api.common.model.routines.UuidGenerateV5.NAMESPACE, value);
	}

	/**
	 * Set the <code>namespace</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setNamespace(org.jooq.Field<java.util.UUID> field) {
		setField(NAMESPACE, field);
	}

	/**
	 * Set the <code>name</code> parameter IN value to the routine
	 */
	public void setName_(java.lang.String value) {
		setValue(com.quizzes.api.common.model.routines.UuidGenerateV5.NAME, value);
	}

	/**
	 * Set the <code>name</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setName_(org.jooq.Field<java.lang.String> field) {
		setField(NAME, field);
	}
}
