/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.records;

import com.quizzes.api.common.model.enums.Lms;
import com.quizzes.api.common.model.tables.Collection;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionRecord extends org.jooq.impl.TableRecordImpl<CollectionRecord> implements org.jooq.Record9<java.util.UUID, java.lang.String, Lms, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.sql.Timestamp> {

	private static final long serialVersionUID = -656512830;

	/**
	 * Setter for <code>public.collection.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.collection.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.collection.external_id</code>.
	 */
	public void setExternalId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.collection.external_id</code>.
	 */
	public java.lang.String getExternalId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.collection.lms_id</code>.
	 */
	public void setLmsId(Lms value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.collection.lms_id</code>.
	 */
	public Lms getLmsId() {
		return (Lms) getValue(2);
	}

	/**
	 * Setter for <code>public.collection.is_collection</code>.
	 */
	public void setIsCollection(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.collection.is_collection</code>.
	 */
	public java.lang.Boolean getIsCollection() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>public.collection.owner_profile_id</code>.
	 */
	public void setOwnerProfileId(java.util.UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.collection.owner_profile_id</code>.
	 */
	public java.util.UUID getOwnerProfileId() {
		return (java.util.UUID) getValue(4);
	}

	/**
	 * Setter for <code>public.collection.collection_data</code>.
	 */
	public void setCollectionData(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.collection.collection_data</code>.
	 */
	public java.lang.String getCollectionData() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.collection.is_lock</code>.
	 */
	public void setIsLock(java.lang.Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.collection.is_lock</code>.
	 */
	public java.lang.Boolean getIsLock() {
		return (java.lang.Boolean) getValue(6);
	}

	/**
	 * Setter for <code>public.collection.is_deleted</code>.
	 */
	public void setIsDeleted(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.collection.is_deleted</code>.
	 */
	public java.lang.Boolean getIsDeleted() {
		return (java.lang.Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.collection.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.collection.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.lang.String, Lms, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.lang.String, Lms, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return Collection.COLLECTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return Collection.COLLECTION.EXTERNAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Lms> field3() {
		return Collection.COLLECTION.LMS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return Collection.COLLECTION.IS_COLLECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field5() {
		return Collection.COLLECTION.OWNER_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return Collection.COLLECTION.COLLECTION_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field7() {
		return Collection.COLLECTION.IS_LOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return Collection.COLLECTION.IS_DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return Collection.COLLECTION.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getExternalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Lms value3() {
		return getLmsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getIsCollection();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value5() {
		return getOwnerProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCollectionData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value7() {
		return getIsLock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getIsDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value2(java.lang.String value) {
		setExternalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value3(Lms value) {
		setLmsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value4(java.lang.Boolean value) {
		setIsCollection(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value5(java.util.UUID value) {
		setOwnerProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value6(java.lang.String value) {
		setCollectionData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value7(java.lang.Boolean value) {
		setIsLock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value8(java.lang.Boolean value) {
		setIsDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value9(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord values(java.util.UUID value1, java.lang.String value2, Lms value3, java.lang.Boolean value4, java.util.UUID value5, java.lang.String value6, java.lang.Boolean value7, java.lang.Boolean value8, java.sql.Timestamp value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CollectionRecord
	 */
	public CollectionRecord() {
		super(Collection.COLLECTION);
	}

	/**
	 * Create a detached, initialised CollectionRecord
	 */
	public CollectionRecord(java.util.UUID id, java.lang.String externalId, Lms lmsId, java.lang.Boolean isCollection, java.util.UUID ownerProfileId, java.lang.String collectionData, java.lang.Boolean isLock, java.lang.Boolean isDeleted, java.sql.Timestamp createdAt) {
		super(Collection.COLLECTION);

		setValue(0, id);
		setValue(1, externalId);
		setValue(2, lmsId);
		setValue(3, isCollection);
		setValue(4, ownerProfileId);
		setValue(5, collectionData);
		setValue(6, isLock);
		setValue(7, isDeleted);
		setValue(8, createdAt);
	}
}
