/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.common.model.tables.records.ContextRecord> implements org.jooq.Record5<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -983900972;

	/**
	 * Setter for <code>public.context.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.context.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.context.collection_id</code>.
	 */
	public void setCollectionId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.context.collection_id</code>.
	 */
	public java.util.UUID getCollectionId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.context.group_id</code>.
	 */
	public void setGroupId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.context.group_id</code>.
	 */
	public java.util.UUID getGroupId() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>public.context.context_data</code>.
	 */
	public void setContextData(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.context.context_data</code>.
	 */
	public java.lang.String getContextData() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.context.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.context.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.common.model.tables.Context.CONTEXT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.quizzes.api.common.model.tables.Context.CONTEXT.COLLECTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.quizzes.api.common.model.tables.Context.CONTEXT.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.quizzes.api.common.model.tables.Context.CONTEXT.CONTEXT_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.quizzes.api.common.model.tables.Context.CONTEXT.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getCollectionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContextData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value2(java.util.UUID value) {
		setCollectionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value3(java.util.UUID value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value4(java.lang.String value) {
		setContextData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value5(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.lang.String value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContextRecord
	 */
	public ContextRecord() {
		super(com.quizzes.api.common.model.tables.Context.CONTEXT);
	}

	/**
	 * Create a detached, initialised ContextRecord
	 */
	public ContextRecord(java.util.UUID id, java.util.UUID collectionId, java.util.UUID groupId, java.lang.String contextData, java.sql.Timestamp createdAt) {
		super(com.quizzes.api.common.model.tables.Context.CONTEXT);

		setValue(0, id);
		setValue(1, collectionId);
		setValue(2, groupId);
		setValue(3, contextData);
		setValue(4, createdAt);
	}
}
