/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextProfileEvent extends org.jooq.impl.TableImpl<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord> {

	private static final long serialVersionUID = -1233308990;

	/**
	 * The singleton instance of <code>public.context_profile_event</code>
	 */
	public static final com.quizzes.api.common.model.jooq.tables.ContextProfileEvent CONTEXT_PROFILE_EVENT = new com.quizzes.api.common.model.jooq.tables.ContextProfileEvent();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord> getRecordType() {
		return com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord.class;
	}

	/**
	 * The column <code>public.context_profile_event.id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context_profile_event.context_profile_id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord, java.util.UUID> CONTEXT_PROFILE_ID = createField("context_profile_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context_profile_event.resource_id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord, java.util.UUID> RESOURCE_ID = createField("resource_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context_profile_event.event_data</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord, java.lang.String> EVENT_DATA = createField("event_data", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new com.quizzes.api.common.binding.PostgresJsonbStringBinding());

	/**
	 * The column <code>public.context_profile_event.created_at</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.context_profile_event</code> table reference
	 */
	public ContextProfileEvent() {
		this("context_profile_event", null);
	}

	/**
	 * Create an aliased <code>public.context_profile_event</code> table reference
	 */
	public ContextProfileEvent(java.lang.String alias) {
		this(alias, com.quizzes.api.common.model.jooq.tables.ContextProfileEvent.CONTEXT_PROFILE_EVENT);
	}

	private ContextProfileEvent(java.lang.String alias, org.jooq.Table<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContextProfileEvent(java.lang.String alias, org.jooq.Table<com.quizzes.api.common.model.jooq.tables.records.ContextProfileEventRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.model.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.model.jooq.tables.ContextProfileEvent as(java.lang.String alias) {
		return new com.quizzes.api.common.model.jooq.tables.ContextProfileEvent(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.model.jooq.tables.ContextProfileEvent rename(java.lang.String name) {
		return new com.quizzes.api.common.model.jooq.tables.ContextProfileEvent(name, null);
	}
}
