/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Group extends org.jooq.impl.TableImpl<com.quizzes.api.common.model.jooq.tables.records.GroupRecord> {

	private static final long serialVersionUID = 1864371330;

	/**
	 * The singleton instance of <code>public.group</code>
	 */
	public static final com.quizzes.api.common.model.jooq.tables.Group GROUP = new com.quizzes.api.common.model.jooq.tables.Group();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.quizzes.api.common.model.jooq.tables.records.GroupRecord> getRecordType() {
		return com.quizzes.api.common.model.jooq.tables.records.GroupRecord.class;
	}

	/**
	 * The column <code>public.group.id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.GroupRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.group.owner_profile_id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.GroupRecord, java.util.UUID> OWNER_PROFILE_ID = createField("owner_profile_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.group.group_data</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.GroupRecord, java.lang.String> GROUP_DATA = createField("group_data", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new com.quizzes.api.common.model.binding.PostgresJsonbStringBinding());

	/**
	 * The column <code>public.group.created_at</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.jooq.tables.records.GroupRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.group</code> table reference
	 */
	public Group() {
		this("group", null);
	}

	/**
	 * Create an aliased <code>public.group</code> table reference
	 */
	public Group(java.lang.String alias) {
		this(alias, com.quizzes.api.common.model.jooq.tables.Group.GROUP);
	}

	private Group(java.lang.String alias, org.jooq.Table<com.quizzes.api.common.model.jooq.tables.records.GroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private Group(java.lang.String alias, org.jooq.Table<com.quizzes.api.common.model.jooq.tables.records.GroupRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.model.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.model.jooq.tables.Group as(java.lang.String alias) {
		return new com.quizzes.api.common.model.jooq.tables.Group(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.model.jooq.tables.Group rename(java.lang.String name) {
		return new com.quizzes.api.common.model.jooq.tables.Group(name, null);
	}
}
