/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.enums;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ContentProvider implements org.jooq.EnumType {

	quizzes("quizzes"),

	gooru("gooru");

	private final java.lang.String literal;

	private ContentProvider(java.lang.String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Schema getSchema() {
		return com.quizzes.api.common.model.jooq.Public.PUBLIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getName() {
		return "content_provider";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
