/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables;

import com.quizzes.api.common.model.Public;
import com.quizzes.api.common.model.tables.records.CollectionOnAirRecord;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionOnAir extends org.jooq.impl.TableImpl<CollectionOnAirRecord> {

	private static final long serialVersionUID = 846973365;

	/**
	 * The singleton instance of <code>public.collection_on_air</code>
	 */
	public static final CollectionOnAir COLLECTION_ON_AIR = new CollectionOnAir();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<CollectionOnAirRecord> getRecordType() {
		return CollectionOnAirRecord.class;
	}

	/**
	 * The column <code>public.collection_on_air.id</code>.
	 */
	public final org.jooq.TableField<CollectionOnAirRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.collection_on_air.class_id</code>.
	 */
	public final org.jooq.TableField<CollectionOnAirRecord, java.lang.String> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.collection_on_air.collection_id</code>.
	 */
	public final org.jooq.TableField<CollectionOnAirRecord, java.lang.String> COLLECTION_ID = createField("collection_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.collection_on_air</code> table reference
	 */
	public CollectionOnAir() {
		this("collection_on_air", null);
	}

	/**
	 * Create an aliased <code>public.collection_on_air</code> table reference
	 */
	public CollectionOnAir(java.lang.String alias) {
		this(alias, CollectionOnAir.COLLECTION_ON_AIR);
	}

	private CollectionOnAir(java.lang.String alias, org.jooq.Table<CollectionOnAirRecord> aliased) {
		this(alias, aliased, null);
	}

	private CollectionOnAir(java.lang.String alias, org.jooq.Table<CollectionOnAirRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionOnAir as(java.lang.String alias) {
		return new CollectionOnAir(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CollectionOnAir rename(java.lang.String name) {
		return new CollectionOnAir(name, null);
	}
}
