/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables;

import com.quizzes.api.common.model.Public;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Context extends org.jooq.impl.TableImpl<com.quizzes.api.common.model.tables.records.ContextRecord> {

	private static final long serialVersionUID = 1352977591;

	/**
	 * The singleton instance of <code>public.context</code>
	 */
	public static final com.quizzes.api.common.model.tables.Context CONTEXT = new com.quizzes.api.common.model.tables.Context();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.quizzes.api.common.model.tables.records.ContextRecord> getRecordType() {
		return com.quizzes.api.common.model.tables.records.ContextRecord.class;
	}

	/**
	 * The column <code>public.context.id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.tables.records.ContextRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context.collection_id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.tables.records.ContextRecord, java.util.UUID> COLLECTION_ID = createField("collection_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context.group_id</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.tables.records.ContextRecord, java.util.UUID> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context.context_data</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.tables.records.ContextRecord, java.lang.Object> CONTEXT_DATA = createField("context_data", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>public.context.created_at</code>.
	 */
	public final org.jooq.TableField<com.quizzes.api.common.model.tables.records.ContextRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.context</code> table reference
	 */
	public Context() {
		this("context", null);
	}

	/**
	 * Create an aliased <code>public.context</code> table reference
	 */
	public Context(java.lang.String alias) {
		this(alias, com.quizzes.api.common.model.tables.Context.CONTEXT);
	}

	private Context(java.lang.String alias, org.jooq.Table<com.quizzes.api.common.model.tables.records.ContextRecord> aliased) {
		this(alias, aliased, null);
	}

	private Context(java.lang.String alias, org.jooq.Table<com.quizzes.api.common.model.tables.records.ContextRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.model.tables.Context as(java.lang.String alias) {
		return new com.quizzes.api.common.model.tables.Context(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.model.tables.Context rename(java.lang.String name) {
		return new com.quizzes.api.common.model.tables.Context(name, null);
	}
}
