/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables;

import com.quizzes.api.common.model.Public;
import com.quizzes.api.common.model.tables.records.ContextProfileRecord;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextProfile extends org.jooq.impl.TableImpl<ContextProfileRecord> {

	private static final long serialVersionUID = 570595885;

	/**
	 * The singleton instance of <code>public.context_profile</code>
	 */
	public static final ContextProfile CONTEXT_PROFILE = new ContextProfile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ContextProfileRecord> getRecordType() {
		return ContextProfileRecord.class;
	}

	/**
	 * The column <code>public.context_profile.id</code>.
	 */
	public final org.jooq.TableField<ContextProfileRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context_profile.context_id</code>.
	 */
	public final org.jooq.TableField<ContextProfileRecord, java.util.UUID> CONTEXT_ID = createField("context_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context_profile.profile_id</code>.
	 */
	public final org.jooq.TableField<ContextProfileRecord, java.util.UUID> PROFILE_ID = createField("profile_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context_profile.current_resource_id</code>.
	 */
	public final org.jooq.TableField<ContextProfileRecord, java.util.UUID> CURRENT_RESOURCE_ID = createField("current_resource_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context_profile.is_complete</code>.
	 */
	public final org.jooq.TableField<ContextProfileRecord, java.lang.Boolean> IS_COMPLETE = createField("is_complete", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.context_profile.created_at</code>.
	 */
	public final org.jooq.TableField<ContextProfileRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.context_profile</code> table reference
	 */
	public ContextProfile() {
		this("context_profile", null);
	}

	/**
	 * Create an aliased <code>public.context_profile</code> table reference
	 */
	public ContextProfile(java.lang.String alias) {
		this(alias, ContextProfile.CONTEXT_PROFILE);
	}

	private ContextProfile(java.lang.String alias, org.jooq.Table<ContextProfileRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContextProfile(java.lang.String alias, org.jooq.Table<ContextProfileRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextProfile as(java.lang.String alias) {
		return new ContextProfile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ContextProfile rename(java.lang.String name) {
		return new ContextProfile(name, null);
	}
}
