/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables;

import com.quizzes.api.common.model.Public;
import com.quizzes.api.common.model.tables.records.EventIndexRecord;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventIndex extends org.jooq.impl.TableImpl<EventIndexRecord> {

	private static final long serialVersionUID = 1779866634;

	/**
	 * The singleton instance of <code>public.event_index</code>
	 */
	public static final EventIndex EVENT_INDEX = new EventIndex();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<EventIndexRecord> getRecordType() {
		return EventIndexRecord.class;
	}

	/**
	 * The column <code>public.event_index.id</code>.
	 */
	public final org.jooq.TableField<EventIndexRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.event_index.collection_unique_id</code>.
	 */
	public final org.jooq.TableField<EventIndexRecord, java.lang.String> COLLECTION_UNIQUE_ID = createField("collection_unique_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.event_index.is_complete</code>.
	 */
	public final org.jooq.TableField<EventIndexRecord, java.lang.Boolean> IS_COMPLETE = createField("is_complete", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>public.event_index.user_id</code>.
	 */
	public final org.jooq.TableField<EventIndexRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.event_index</code> table reference
	 */
	public EventIndex() {
		this("event_index", null);
	}

	/**
	 * Create an aliased <code>public.event_index</code> table reference
	 */
	public EventIndex(java.lang.String alias) {
		this(alias, EventIndex.EVENT_INDEX);
	}

	private EventIndex(java.lang.String alias, org.jooq.Table<EventIndexRecord> aliased) {
		this(alias, aliased, null);
	}

	private EventIndex(java.lang.String alias, org.jooq.Table<EventIndexRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventIndex as(java.lang.String alias) {
		return new EventIndex(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EventIndex rename(java.lang.String name) {
		return new EventIndex(name, null);
	}
}
