/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables;

import com.quizzes.api.common.model.Public;
import com.quizzes.api.common.model.tables.records.GroupRecord;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Group extends org.jooq.impl.TableImpl<GroupRecord> {

	private static final long serialVersionUID = 1414219208;

	/**
	 * The singleton instance of <code>public.group</code>
	 */
	public static final Group GROUP = new Group();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<GroupRecord> getRecordType() {
		return GroupRecord.class;
	}

	/**
	 * The column <code>public.group.id</code>.
	 */
	public final org.jooq.TableField<GroupRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.group.owner_profile_id</code>.
	 */
	public final org.jooq.TableField<GroupRecord, java.util.UUID> OWNER_PROFILE_ID = createField("owner_profile_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.group.group_data</code>.
	 */
	public final org.jooq.TableField<GroupRecord, java.lang.String> GROUP_DATA = createField("group_data", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new com.quizzes.api.common.model.PostgresJSONGsonBinding());

	/**
	 * The column <code>public.group.created_at</code>.
	 */
	public final org.jooq.TableField<GroupRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.group</code> table reference
	 */
	public Group() {
		this("group", null);
	}

	/**
	 * Create an aliased <code>public.group</code> table reference
	 */
	public Group(java.lang.String alias) {
		this(alias, Group.GROUP);
	}

	private Group(java.lang.String alias, org.jooq.Table<GroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private Group(java.lang.String alias, org.jooq.Table<GroupRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Group as(java.lang.String alias) {
		return new Group(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Group rename(java.lang.String name) {
		return new Group(name, null);
	}
}
