/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables;

import com.quizzes.api.common.model.Public;
import com.quizzes.api.common.model.tables.records.ProfileRecord;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profile extends org.jooq.impl.TableImpl<ProfileRecord> {

	private static final long serialVersionUID = -172976305;

	/**
	 * The singleton instance of <code>public.profile</code>
	 */
	public static final Profile PROFILE = new Profile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ProfileRecord> getRecordType() {
		return ProfileRecord.class;
	}

	/**
	 * The column <code>public.profile.id</code>.
	 */
	public final org.jooq.TableField<ProfileRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.profile.external_id</code>.
	 */
	public final org.jooq.TableField<ProfileRecord, java.lang.String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.profile.lms_id</code>.
	 */
	public final org.jooq.TableField<ProfileRecord, com.quizzes.api.common.model.enums.Lms> LMS_ID = createField("lms_id", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.quizzes.api.common.model.enums.Lms.class), this, "");

	/**
	 * The column <code>public.profile.profile_data</code>.
	 */
	public final org.jooq.TableField<ProfileRecord, java.lang.String> PROFILE_DATA = createField("profile_data", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new com.quizzes.api.common.model.PostgresJSONGsonBinding());

	/**
	 * The column <code>public.profile.created_at</code>.
	 */
	public final org.jooq.TableField<ProfileRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.profile</code> table reference
	 */
	public Profile() {
		this("profile", null);
	}

	/**
	 * Create an aliased <code>public.profile</code> table reference
	 */
	public Profile(java.lang.String alias) {
		this(alias, Profile.PROFILE);
	}

	private Profile(java.lang.String alias, org.jooq.Table<ProfileRecord> aliased) {
		this(alias, aliased, null);
	}

	private Profile(java.lang.String alias, org.jooq.Table<ProfileRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Profile as(java.lang.String alias) {
		return new Profile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Profile rename(java.lang.String name) {
		return new Profile(name, null);
	}
}
