/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Context implements java.io.Serializable {

	private static final long serialVersionUID = -70486127;

	private java.util.UUID     id;
	private java.util.UUID     collectionId;
	private java.util.UUID     groupId;
	private java.lang.String   contextData;
	private java.sql.Timestamp createdAt;

	public Context() {}

	public Context(
		java.util.UUID     id,
		java.util.UUID     collectionId,
		java.util.UUID     groupId,
		java.lang.String   contextData,
		java.sql.Timestamp createdAt
	) {
		this.id = id;
		this.collectionId = collectionId;
		this.groupId = groupId;
		this.contextData = contextData;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(java.util.UUID collectionId) {
		this.collectionId = collectionId;
	}

	public java.util.UUID getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.util.UUID groupId) {
		this.groupId = groupId;
	}

	public java.lang.String getContextData() {
		return this.contextData;
	}

	public void setContextData(java.lang.String contextData) {
		this.contextData = contextData;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
