/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventIndex implements java.io.Serializable {

	private static final long serialVersionUID = 1133284964;

	private java.util.UUID    id;
	private java.lang.String  collectionUniqueId;
	private java.lang.Boolean isComplete;
	private java.lang.String  userId;

	public EventIndex() {}

	public EventIndex(
		java.util.UUID    id,
		java.lang.String  collectionUniqueId,
		java.lang.Boolean isComplete,
		java.lang.String  userId
	) {
		this.id = id;
		this.collectionUniqueId = collectionUniqueId;
		this.isComplete = isComplete;
		this.userId = userId;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getCollectionUniqueId() {
		return this.collectionUniqueId;
	}

	public void setCollectionUniqueId(java.lang.String collectionUniqueId) {
		this.collectionUniqueId = collectionUniqueId;
	}

	public java.lang.Boolean getIsComplete() {
		return this.isComplete;
	}

	public void setIsComplete(java.lang.Boolean isComplete) {
		this.isComplete = isComplete;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}
}
