/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupProfile implements java.io.Serializable {

	private static final long serialVersionUID = -585096366;

	private java.util.UUID     id;
	private java.util.UUID     groupId;
	private java.util.UUID     profileId;
	private java.sql.Timestamp createdAt;

	public GroupProfile() {}

	public GroupProfile(
		java.util.UUID     id,
		java.util.UUID     groupId,
		java.util.UUID     profileId,
		java.sql.Timestamp createdAt
	) {
		this.id = id;
		this.groupId = groupId;
		this.profileId = profileId;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.util.UUID groupId) {
		this.groupId = groupId;
	}

	public java.util.UUID getProfileId() {
		return this.profileId;
	}

	public void setProfileId(java.util.UUID profileId) {
		this.profileId = profileId;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
