/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Group implements java.io.Serializable {

	private static final long serialVersionUID = -1922763644;

	private java.util.UUID     id;
	private java.util.UUID     ownerProfileId;
	private java.lang.Object   groupData;
	private java.sql.Timestamp createdAt;

	public Group() {}

	public Group(
		java.util.UUID     id,
		java.util.UUID     ownerProfileId,
		java.lang.Object   groupData,
		java.sql.Timestamp createdAt
	) {
		this.id = id;
		this.ownerProfileId = ownerProfileId;
		this.groupData = groupData;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getOwnerProfileId() {
		return this.ownerProfileId;
	}

	public void setOwnerProfileId(java.util.UUID ownerProfileId) {
		this.ownerProfileId = ownerProfileId;
	}

	public java.lang.Object getGroupData() {
		return this.groupData;
	}

	public void setGroupData(java.lang.Object groupData) {
		this.groupData = groupData;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
