/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profile implements java.io.Serializable {

	private static final long serialVersionUID = -32421586;

	private java.util.UUID                   id;
	private java.lang.String                 externalId;
	private com.quizzes.api.common.model.enums.Lms lmsId;
	private java.lang.Object                 profileData;
	private java.sql.Timestamp               createdAt;

	public Profile() {}

	public Profile(
		java.util.UUID                   id,
		java.lang.String                 externalId,
		com.quizzes.api.common.model.enums.Lms lmsId,
		java.lang.Object                 profileData,
		java.sql.Timestamp               createdAt
	) {
		this.id = id;
		this.externalId = externalId;
		this.lmsId = lmsId;
		this.profileData = profileData;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}

	public com.quizzes.api.common.model.enums.Lms getLmsId() {
		return this.lmsId;
	}

	public void setLmsId(com.quizzes.api.common.model.enums.Lms lmsId) {
		this.lmsId = lmsId;
	}

	public java.lang.Object getProfileData() {
		return this.profileData;
	}

	public void setProfileData(java.lang.Object profileData) {
		this.profileData = profileData;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
