/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Resource implements java.io.Serializable {

	private static final long serialVersionUID = -1261559813;

	private java.util.UUID                   id;
	private java.lang.String                 externalId;
	private com.quizzes.api.common.model.enums.Lms lmsId;
	private java.util.UUID                   collectionId;
	private java.lang.Boolean                isResource;
	private java.util.UUID                   ownerProfileId;
	private java.lang.String                 resourceData;
	private java.lang.Short                  sequence;
	private java.lang.Boolean                isDeleted;
	private java.sql.Timestamp               createdAt;

	public Resource() {}

	public Resource(
		java.util.UUID                   id,
		java.lang.String                 externalId,
		com.quizzes.api.common.model.enums.Lms lmsId,
		java.util.UUID                   collectionId,
		java.lang.Boolean                isResource,
		java.util.UUID                   ownerProfileId,
		java.lang.String                 resourceData,
		java.lang.Short                  sequence,
		java.lang.Boolean                isDeleted,
		java.sql.Timestamp               createdAt
	) {
		this.id = id;
		this.externalId = externalId;
		this.lmsId = lmsId;
		this.collectionId = collectionId;
		this.isResource = isResource;
		this.ownerProfileId = ownerProfileId;
		this.resourceData = resourceData;
		this.sequence = sequence;
		this.isDeleted = isDeleted;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}

	public com.quizzes.api.common.model.enums.Lms getLmsId() {
		return this.lmsId;
	}

	public void setLmsId(com.quizzes.api.common.model.enums.Lms lmsId) {
		this.lmsId = lmsId;
	}

	public java.util.UUID getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(java.util.UUID collectionId) {
		this.collectionId = collectionId;
	}

	public java.lang.Boolean getIsResource() {
		return this.isResource;
	}

	public void setIsResource(java.lang.Boolean isResource) {
		this.isResource = isResource;
	}

	public java.util.UUID getOwnerProfileId() {
		return this.ownerProfileId;
	}

	public void setOwnerProfileId(java.util.UUID ownerProfileId) {
		this.ownerProfileId = ownerProfileId;
	}

	public java.lang.String getResourceData() {
		return this.resourceData;
	}

	public void setResourceData(java.lang.String resourceData) {
		this.resourceData = resourceData;
	}

	public java.lang.Short getSequence() {
		return this.sequence;
	}

	public void setSequence(java.lang.Short sequence) {
		this.sequence = sequence;
	}

	public java.lang.Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
