/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collection implements java.io.Serializable {

	private static final long serialVersionUID = -814831391;

	private java.util.UUID                                          id;
	private java.lang.String                                        externalId;
	private java.lang.String                                        externalParentId;
	private java.lang.Boolean                                       isCollection;
	private java.util.UUID                                          ownerProfileId;
	private java.lang.String                                        collectionData;
	private java.lang.Boolean                                       isLocked;
	private java.lang.Boolean                                       isDeleted;
	private java.sql.Timestamp                                      createdAt;
	private java.sql.Timestamp                                      updatedAt;
	private com.quizzes.api.common.model.jooq.enums.ContentProvider contentProvider;

	public Collection() {}

	public Collection(
		java.util.UUID                                          id,
		java.lang.String                                        externalId,
		java.lang.String                                        externalParentId,
		java.lang.Boolean                                       isCollection,
		java.util.UUID                                          ownerProfileId,
		java.lang.String                                        collectionData,
		java.lang.Boolean                                       isLocked,
		java.lang.Boolean                                       isDeleted,
		java.sql.Timestamp                                      createdAt,
		java.sql.Timestamp                                      updatedAt,
		com.quizzes.api.common.model.jooq.enums.ContentProvider contentProvider
	) {
		this.id = id;
		this.externalId = externalId;
		this.externalParentId = externalParentId;
		this.isCollection = isCollection;
		this.ownerProfileId = ownerProfileId;
		this.collectionData = collectionData;
		this.isLocked = isLocked;
		this.isDeleted = isDeleted;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.contentProvider = contentProvider;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}

	public java.lang.String getExternalParentId() {
		return this.externalParentId;
	}

	public void setExternalParentId(java.lang.String externalParentId) {
		this.externalParentId = externalParentId;
	}

	public java.lang.Boolean getIsCollection() {
		return this.isCollection;
	}

	public void setIsCollection(java.lang.Boolean isCollection) {
		this.isCollection = isCollection;
	}

	public java.util.UUID getOwnerProfileId() {
		return this.ownerProfileId;
	}

	public void setOwnerProfileId(java.util.UUID ownerProfileId) {
		this.ownerProfileId = ownerProfileId;
	}

	public java.lang.String getCollectionData() {
		return this.collectionData;
	}

	public void setCollectionData(java.lang.String collectionData) {
		this.collectionData = collectionData;
	}

	public java.lang.Boolean getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(java.lang.Boolean isLocked) {
		this.isLocked = isLocked;
	}

	public java.lang.Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public java.sql.Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(java.sql.Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public com.quizzes.api.common.model.jooq.enums.ContentProvider getContentProvider() {
		return this.contentProvider;
	}

	public void setContentProvider(com.quizzes.api.common.model.jooq.enums.ContentProvider contentProvider) {
		this.contentProvider = contentProvider;
	}
}
