/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrentContextProfile implements java.io.Serializable {

	private static final long serialVersionUID = 506641036;

	private java.util.UUID contextId;
	private java.util.UUID profileId;
	private java.util.UUID contextProfileId;

	public CurrentContextProfile() {}

	public CurrentContextProfile(
		java.util.UUID contextId,
		java.util.UUID profileId,
		java.util.UUID contextProfileId
	) {
		this.contextId = contextId;
		this.profileId = profileId;
		this.contextProfileId = contextProfileId;
	}

	public java.util.UUID getContextId() {
		return this.contextId;
	}

	public void setContextId(java.util.UUID contextId) {
		this.contextId = contextId;
	}

	public java.util.UUID getProfileId() {
		return this.profileId;
	}

	public void setProfileId(java.util.UUID profileId) {
		this.profileId = profileId;
	}

	public java.util.UUID getContextProfileId() {
		return this.contextProfileId;
	}

	public void setContextProfileId(java.util.UUID contextProfileId) {
		this.contextProfileId = contextProfileId;
	}
}
