/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Session implements java.io.Serializable {

	private static final long serialVersionUID = 307537713;

	private java.util.UUID     id;
	private java.util.UUID     profileId;
	private java.sql.Timestamp createdAt;
	private java.sql.Timestamp lastAccessAt;

	public Session() {}

	public Session(
		java.util.UUID     id,
		java.util.UUID     profileId,
		java.sql.Timestamp createdAt,
		java.sql.Timestamp lastAccessAt
	) {
		this.id = id;
		this.profileId = profileId;
		this.createdAt = createdAt;
		this.lastAccessAt = lastAccessAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getProfileId() {
		return this.profileId;
	}

	public void setProfileId(java.util.UUID profileId) {
		this.profileId = profileId;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public java.sql.Timestamp getLastAccessAt() {
		return this.lastAccessAt;
	}

	public void setLastAccessAt(java.sql.Timestamp lastAccessAt) {
		this.lastAccessAt = lastAccessAt;
	}
}
