/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _UpdateUpdatedAt extends org.jooq.impl.AbstractRoutine<java.lang.Object> {

	private static final long serialVersionUID = 605388606;

	/**
	 * The parameter <code>public._update_updated_at.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

	/**
	 * Create a new routine call instance
	 */
	public _UpdateUpdatedAt() {
		super("_update_updated_at", com.quizzes.api.core.model.jooq.Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

		setReturnParameter(RETURN_VALUE);
	}
}
