/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.enums;

import com.quizzes.api.common.model.Public;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Lms implements org.jooq.EnumType {

	quizzes("quizzes"),

	gooru("gooru"),

	its_learning("its_learning");

	private final java.lang.String literal;

	private Lms(java.lang.String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Schema getSchema() {
		return Public.PUBLIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getName() {
		return "lms";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
