/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all stored procedures and functions in public
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>public._update_updated_at</code>
	 */
	public static java.lang.Object _UpdateUpdatedAt(org.jooq.Configuration configuration) {
		com.quizzes.api.core.model.jooq.routines._UpdateUpdatedAt f = new com.quizzes.api.core.model.jooq.routines._UpdateUpdatedAt();

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public._update_updated_at</code> as a field
	 */
	public static org.jooq.Field<java.lang.Object> _UpdateUpdatedAt() {
		com.quizzes.api.core.model.jooq.routines._UpdateUpdatedAt f = new com.quizzes.api.core.model.jooq.routines._UpdateUpdatedAt();

		return f.asField();
	}
}
