/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.context
	 */
	public static final com.quizzes.api.core.model.jooq.tables.Context CONTEXT = com.quizzes.api.core.model.jooq.tables.Context.CONTEXT;

	/**
	 * The table public.context_profile
	 */
	public static final com.quizzes.api.core.model.jooq.tables.ContextProfile CONTEXT_PROFILE = com.quizzes.api.core.model.jooq.tables.ContextProfile.CONTEXT_PROFILE;

	/**
	 * The table public.context_profile_event
	 */
	public static final com.quizzes.api.core.model.jooq.tables.ContextProfileEvent CONTEXT_PROFILE_EVENT = com.quizzes.api.core.model.jooq.tables.ContextProfileEvent.CONTEXT_PROFILE_EVENT;

	/**
	 * The table public.current_context_profile
	 */
	public static final com.quizzes.api.core.model.jooq.tables.CurrentContextProfile CURRENT_CONTEXT_PROFILE = com.quizzes.api.core.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE;
}
