version: 0.0
os: linux
files:
#  - source: quizzes-api.service
#  destination: /etc/systemd/system/
  - source: quizzes-api.jar
    destination: /opt/quizzes-api/
hooks:
  AfterInstall:
    - location: after-install.sh
      timeout: 180
  ApplicationStart:
    - location: start.sh
      timeout: 180
  ValidateService:
    - location: check.sh
      timeout: 180
