version: 0.0
os: linux
files:
  - source: quizzes-api.jar
    destination: /opt/quizzes-api/
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 180
  AfterInstall:
    - location: after-install.sh
      timeout: 180
  ApplicationStart:
    - location: start.sh
      timeout: 180
  ValidateService:
    - location: check.sh
      timeout: 180
