/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionOnAir implements java.io.Serializable {

	private static final long serialVersionUID = -433813052;

	private java.util.UUID   id;
	private java.lang.String classId;
	private java.lang.String collectionId;

	public CollectionOnAir() {}

	public CollectionOnAir(
		java.util.UUID   id,
		java.lang.String classId,
		java.lang.String collectionId
	) {
		this.id = id;
		this.classId = classId;
		this.collectionId = collectionId;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getClassId() {
		return this.classId;
	}

	public void setClassId(java.lang.String classId) {
		this.classId = classId;
	}

	public java.lang.String getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(java.lang.String collectionId) {
		this.collectionId = collectionId;
	}
}
