/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collection implements java.io.Serializable {

	private static final long serialVersionUID = -746222383;

	private java.util.UUID                   id;
	private java.lang.String                 externalId;
	private java.lang.Boolean                isCollection;
	private java.util.UUID                   ownerProfileId;
	private com.quizzes.api.common.enums.Lms lmsId;
	private java.lang.Object                 collectionBody;
	private java.lang.Boolean                isDeleted;
	private java.sql.Timestamp               createdAt;

	public Collection() {}

	public Collection(
		java.util.UUID                   id,
		java.lang.String                 externalId,
		java.lang.Boolean                isCollection,
		java.util.UUID                   ownerProfileId,
		com.quizzes.api.common.enums.Lms lmsId,
		java.lang.Object                 collectionBody,
		java.lang.Boolean                isDeleted,
		java.sql.Timestamp               createdAt
	) {
		this.id = id;
		this.externalId = externalId;
		this.isCollection = isCollection;
		this.ownerProfileId = ownerProfileId;
		this.lmsId = lmsId;
		this.collectionBody = collectionBody;
		this.isDeleted = isDeleted;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}

	public java.lang.Boolean getIsCollection() {
		return this.isCollection;
	}

	public void setIsCollection(java.lang.Boolean isCollection) {
		this.isCollection = isCollection;
	}

	public java.util.UUID getOwnerProfileId() {
		return this.ownerProfileId;
	}

	public void setOwnerProfileId(java.util.UUID ownerProfileId) {
		this.ownerProfileId = ownerProfileId;
	}

	public com.quizzes.api.common.enums.Lms getLmsId() {
		return this.lmsId;
	}

	public void setLmsId(com.quizzes.api.common.enums.Lms lmsId) {
		this.lmsId = lmsId;
	}

	public java.lang.Object getCollectionBody() {
		return this.collectionBody;
	}

	public void setCollectionBody(java.lang.Object collectionBody) {
		this.collectionBody = collectionBody;
	}

	public java.lang.Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
