/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Context implements java.io.Serializable {

	private static final long serialVersionUID = 1329970756;

	private java.util.UUID     id;
	private java.util.UUID     collectionId;
	private java.lang.Object   contextBody;
	private java.sql.Timestamp createdAt;

	public Context() {}

	public Context(
		java.util.UUID     id,
		java.util.UUID     collectionId,
		java.lang.Object   contextBody,
		java.sql.Timestamp createdAt
	) {
		this.id = id;
		this.collectionId = collectionId;
		this.contextBody = contextBody;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(java.util.UUID collectionId) {
		this.collectionId = collectionId;
	}

	public java.lang.Object getContextBody() {
		return this.contextBody;
	}

	public void setContextBody(java.lang.Object contextBody) {
		this.contextBody = contextBody;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
