/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event implements java.io.Serializable {

	private static final long serialVersionUID = 325883639;

	private java.util.UUID     id;
	private java.util.UUID     eventIndex;
	private java.sql.Timestamp createdAt;
	private java.lang.Object   eventBody;

	public Event() {}

	public Event(
		java.util.UUID     id,
		java.util.UUID     eventIndex,
		java.sql.Timestamp createdAt,
		java.lang.Object   eventBody
	) {
		this.id = id;
		this.eventIndex = eventIndex;
		this.createdAt = createdAt;
		this.eventBody = eventBody;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getEventIndex() {
		return this.eventIndex;
	}

	public void setEventIndex(java.util.UUID eventIndex) {
		this.eventIndex = eventIndex;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public java.lang.Object getEventBody() {
		return this.eventBody;
	}

	public void setEventBody(java.lang.Object eventBody) {
		this.eventBody = eventBody;
	}
}
