/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profile implements java.io.Serializable {

	private static final long serialVersionUID = -1094943406;

	private java.util.UUID     id;
	private java.lang.String   externalId;
	private java.lang.Object   profileBody;
	private java.sql.Timestamp createdAt;

	public Profile() {}

	public Profile(
		java.util.UUID     id,
		java.lang.String   externalId,
		java.lang.Object   profileBody,
		java.sql.Timestamp createdAt
	) {
		this.id = id;
		this.externalId = externalId;
		this.profileBody = profileBody;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}

	public java.lang.Object getProfileBody() {
		return this.profileBody;
	}

	public void setProfileBody(java.lang.Object profileBody) {
		this.profileBody = profileBody;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
