/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.common.model.jooq.tables.records.CollectionRecord> implements org.jooq.Record11<java.util.UUID, java.lang.String, java.lang.String, com.quizzes.api.common.model.jooq.enums.Lms, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1267335753;

	/**
	 * Setter for <code>public.collection.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.collection.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.collection.external_id</code>.
	 */
	public void setExternalId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.collection.external_id</code>.
	 */
	public java.lang.String getExternalId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.collection.external_parent_id</code>.
	 */
	public void setExternalParentId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.collection.external_parent_id</code>.
	 */
	public java.lang.String getExternalParentId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.collection.lms_id</code>.
	 */
	public void setLmsId(com.quizzes.api.common.model.jooq.enums.Lms value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.collection.lms_id</code>.
	 */
	public com.quizzes.api.common.model.jooq.enums.Lms getLmsId() {
		return (com.quizzes.api.common.model.jooq.enums.Lms) getValue(3);
	}

	/**
	 * Setter for <code>public.collection.is_collection</code>.
	 */
	public void setIsCollection(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.collection.is_collection</code>.
	 */
	public java.lang.Boolean getIsCollection() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.collection.owner_profile_id</code>.
	 */
	public void setOwnerProfileId(java.util.UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.collection.owner_profile_id</code>.
	 */
	public java.util.UUID getOwnerProfileId() {
		return (java.util.UUID) getValue(5);
	}

	/**
	 * Setter for <code>public.collection.collection_data</code>.
	 */
	public void setCollectionData(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.collection.collection_data</code>.
	 */
	public java.lang.String getCollectionData() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.collection.is_locked</code>.
	 */
	public void setIsLocked(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.collection.is_locked</code>.
	 */
	public java.lang.Boolean getIsLocked() {
		return (java.lang.Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.collection.is_deleted</code>.
	 */
	public void setIsDeleted(java.lang.Boolean value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.collection.is_deleted</code>.
	 */
	public java.lang.Boolean getIsDeleted() {
		return (java.lang.Boolean) getValue(8);
	}

	/**
	 * Setter for <code>public.collection.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.collection.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>public.collection.updated_at</code>.
	 */
	public void setUpdatedAt(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.collection.updated_at</code>.
	 */
	public java.sql.Timestamp getUpdatedAt() {
		return (java.sql.Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.util.UUID, java.lang.String, java.lang.String, com.quizzes.api.common.model.jooq.enums.Lms, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.util.UUID, java.lang.String, java.lang.String, com.quizzes.api.common.model.jooq.enums.Lms, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.EXTERNAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.EXTERNAL_PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.quizzes.api.common.model.jooq.enums.Lms> field4() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.LMS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.IS_COLLECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field6() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.OWNER_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.COLLECTION_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.IS_LOCKED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field9() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.IS_DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getExternalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getExternalParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.model.jooq.enums.Lms value4() {
		return getLmsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getIsCollection();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value6() {
		return getOwnerProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCollectionData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getIsLocked();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value9() {
		return getIsDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value2(java.lang.String value) {
		setExternalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value3(java.lang.String value) {
		setExternalParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value4(com.quizzes.api.common.model.jooq.enums.Lms value) {
		setLmsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value5(java.lang.Boolean value) {
		setIsCollection(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value6(java.util.UUID value) {
		setOwnerProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value7(java.lang.String value) {
		setCollectionData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value8(java.lang.Boolean value) {
		setIsLocked(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value9(java.lang.Boolean value) {
		setIsDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value10(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value11(java.sql.Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord values(java.util.UUID value1, java.lang.String value2, java.lang.String value3, com.quizzes.api.common.model.jooq.enums.Lms value4, java.lang.Boolean value5, java.util.UUID value6, java.lang.String value7, java.lang.Boolean value8, java.lang.Boolean value9, java.sql.Timestamp value10, java.sql.Timestamp value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CollectionRecord
	 */
	public CollectionRecord() {
		super(com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION);
	}

	/**
	 * Create a detached, initialised CollectionRecord
	 */
	public CollectionRecord(java.util.UUID id, java.lang.String externalId, java.lang.String externalParentId, com.quizzes.api.common.model.jooq.enums.Lms lmsId, java.lang.Boolean isCollection, java.util.UUID ownerProfileId, java.lang.String collectionData, java.lang.Boolean isLocked, java.lang.Boolean isDeleted, java.sql.Timestamp createdAt, java.sql.Timestamp updatedAt) {
		super(com.quizzes.api.common.model.jooq.tables.Collection.COLLECTION);

		setValue(0, id);
		setValue(1, externalId);
		setValue(2, externalParentId);
		setValue(3, lmsId);
		setValue(4, isCollection);
		setValue(5, ownerProfileId);
		setValue(6, collectionData);
		setValue(7, isLocked);
		setValue(8, isDeleted);
		setValue(9, createdAt);
		setValue(10, updatedAt);
	}
}
