/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.common.model.jooq.tables.records.ContextRecord> implements org.jooq.Record8<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp, java.lang.Boolean> {

	private static final long serialVersionUID = -1029041253;

	/**
	 * Setter for <code>public.context.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.context.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.context.group_id</code>.
	 */
	public void setGroupId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.context.group_id</code>.
	 */
	public java.util.UUID getGroupId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.context.collection_id</code>.
	 */
	public void setCollectionId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.context.collection_id</code>.
	 */
	public java.util.UUID getCollectionId() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>public.context.context_data</code>.
	 */
	public void setContextData(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.context.context_data</code>.
	 */
	public java.lang.String getContextData() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.context.is_deleted</code>.
	 */
	public void setIsDeleted(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.context.is_deleted</code>.
	 */
	public java.lang.Boolean getIsDeleted() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.context.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.context.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.context.updated_at</code>.
	 */
	public void setUpdatedAt(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.context.updated_at</code>.
	 */
	public java.sql.Timestamp getUpdatedAt() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.context.is_active</code>.
	 */
	public void setIsActive(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.context.is_active</code>.
	 */
	public java.lang.Boolean getIsActive() {
		return (java.lang.Boolean) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.COLLECTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.CONTEXT_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.IS_DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return com.quizzes.api.common.model.jooq.tables.Context.CONTEXT.IS_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getCollectionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContextData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getIsDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getIsActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value2(java.util.UUID value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value3(java.util.UUID value) {
		setCollectionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value4(java.lang.String value) {
		setContextData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value5(java.lang.Boolean value) {
		setIsDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value6(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value7(java.sql.Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord value8(java.lang.Boolean value) {
		setIsActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContextRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.lang.String value4, java.lang.Boolean value5, java.sql.Timestamp value6, java.sql.Timestamp value7, java.lang.Boolean value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContextRecord
	 */
	public ContextRecord() {
		super(com.quizzes.api.common.model.jooq.tables.Context.CONTEXT);
	}

	/**
	 * Create a detached, initialised ContextRecord
	 */
	public ContextRecord(java.util.UUID id, java.util.UUID groupId, java.util.UUID collectionId, java.lang.String contextData, java.lang.Boolean isDeleted, java.sql.Timestamp createdAt, java.sql.Timestamp updatedAt, java.lang.Boolean isActive) {
		super(com.quizzes.api.common.model.jooq.tables.Context.CONTEXT);

		setValue(0, id);
		setValue(1, groupId);
		setValue(2, collectionId);
		setValue(3, contextData);
		setValue(4, isDeleted);
		setValue(5, createdAt);
		setValue(6, updatedAt);
		setValue(7, isActive);
	}
}
