/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrentContextProfileRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.common.model.jooq.tables.records.CurrentContextProfileRecord> implements org.jooq.Record3<java.util.UUID, java.util.UUID, java.util.UUID> {

	private static final long serialVersionUID = -1651203189;

	/**
	 * Setter for <code>public.current_context_profile.context_id</code>.
	 */
	public void setContextId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.current_context_profile.context_id</code>.
	 */
	public java.util.UUID getContextId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.current_context_profile.profile_id</code>.
	 */
	public void setProfileId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.current_context_profile.profile_id</code>.
	 */
	public java.util.UUID getProfileId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.current_context_profile.context_profile_id</code>.
	 */
	public void setContextProfileId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.current_context_profile.context_profile_id</code>.
	 */
	public java.util.UUID getContextProfileId() {
		return (java.util.UUID) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.util.UUID, java.util.UUID> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.util.UUID, java.util.UUID> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.common.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE.CONTEXT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.quizzes.api.common.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE.PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.quizzes.api.common.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE.CONTEXT_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getContextId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getContextProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord value1(java.util.UUID value) {
		setContextId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord value2(java.util.UUID value) {
		setProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord value3(java.util.UUID value) {
		setContextProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentContextProfileRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CurrentContextProfileRecord
	 */
	public CurrentContextProfileRecord() {
		super(com.quizzes.api.common.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE);
	}

	/**
	 * Create a detached, initialised CurrentContextProfileRecord
	 */
	public CurrentContextProfileRecord(java.util.UUID contextId, java.util.UUID profileId, java.util.UUID contextProfileId) {
		super(com.quizzes.api.common.model.jooq.tables.CurrentContextProfile.CURRENT_CONTEXT_PROFILE);

		setValue(0, contextId);
		setValue(1, profileId);
		setValue(2, contextProfileId);
	}
}
