/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventIndexRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.common.model.jooq.tables.records.EventIndexRecord> implements org.jooq.Record4<java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.String> {

	private static final long serialVersionUID = 2128592617;

	/**
	 * Setter for <code>public.event_index.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.event_index.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.event_index.collection_unique_id</code>.
	 */
	public void setCollectionUniqueId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.event_index.collection_unique_id</code>.
	 */
	public java.lang.String getCollectionUniqueId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.event_index.is_complete</code>.
	 */
	public void setIsComplete(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.event_index.is_complete</code>.
	 */
	public java.lang.Boolean getIsComplete() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>public.event_index.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.event_index.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.lang.String, java.lang.Boolean, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.common.model.jooq.tables.EventIndex.EVENT_INDEX.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.quizzes.api.common.model.jooq.tables.EventIndex.EVENT_INDEX.COLLECTION_UNIQUE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return com.quizzes.api.common.model.jooq.tables.EventIndex.EVENT_INDEX.IS_COMPLETE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.quizzes.api.common.model.jooq.tables.EventIndex.EVENT_INDEX.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCollectionUniqueId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getIsComplete();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventIndexRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventIndexRecord value2(java.lang.String value) {
		setCollectionUniqueId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventIndexRecord value3(java.lang.Boolean value) {
		setIsComplete(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventIndexRecord value4(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventIndexRecord values(java.util.UUID value1, java.lang.String value2, java.lang.Boolean value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventIndexRecord
	 */
	public EventIndexRecord() {
		super(com.quizzes.api.common.model.jooq.tables.EventIndex.EVENT_INDEX);
	}

	/**
	 * Create a detached, initialised EventIndexRecord
	 */
	public EventIndexRecord(java.util.UUID id, java.lang.String collectionUniqueId, java.lang.Boolean isComplete, java.lang.String userId) {
		super(com.quizzes.api.common.model.jooq.tables.EventIndex.EVENT_INDEX);

		setValue(0, id);
		setValue(1, collectionUniqueId);
		setValue(2, isComplete);
		setValue(3, userId);
	}
}
