/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.model.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceRecord extends org.jooq.impl.TableRecordImpl<com.quizzes.api.common.model.jooq.tables.records.ResourceRecord> implements org.jooq.Record11<java.util.UUID, java.lang.String, java.util.UUID, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Short, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp, com.quizzes.api.common.model.jooq.enums.ContentProvider> {

	private static final long serialVersionUID = 1261830976;

	/**
	 * Setter for <code>public.resource.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.resource.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.resource.external_id</code>.
	 */
	public void setExternalId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.resource.external_id</code>.
	 */
	public java.lang.String getExternalId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.resource.collection_id</code>.
	 */
	public void setCollectionId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.resource.collection_id</code>.
	 */
	public java.util.UUID getCollectionId() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>public.resource.is_resource</code>.
	 */
	public void setIsResource(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.resource.is_resource</code>.
	 */
	public java.lang.Boolean getIsResource() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>public.resource.owner_profile_id</code>.
	 */
	public void setOwnerProfileId(java.util.UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.resource.owner_profile_id</code>.
	 */
	public java.util.UUID getOwnerProfileId() {
		return (java.util.UUID) getValue(4);
	}

	/**
	 * Setter for <code>public.resource.resource_data</code>.
	 */
	public void setResourceData(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.resource.resource_data</code>.
	 */
	public java.lang.String getResourceData() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.resource.sequence</code>.
	 */
	public void setSequence(java.lang.Short value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.resource.sequence</code>.
	 */
	public java.lang.Short getSequence() {
		return (java.lang.Short) getValue(6);
	}

	/**
	 * Setter for <code>public.resource.is_deleted</code>.
	 */
	public void setIsDeleted(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.resource.is_deleted</code>.
	 */
	public java.lang.Boolean getIsDeleted() {
		return (java.lang.Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.resource.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.resource.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>public.resource.updated_at</code>.
	 */
	public void setUpdatedAt(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.resource.updated_at</code>.
	 */
	public java.sql.Timestamp getUpdatedAt() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>public.resource.content_provider</code>.
	 */
	public void setContentProvider(com.quizzes.api.common.model.jooq.enums.ContentProvider value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.resource.content_provider</code>.
	 */
	public com.quizzes.api.common.model.jooq.enums.ContentProvider getContentProvider() {
		return (com.quizzes.api.common.model.jooq.enums.ContentProvider) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.util.UUID, java.lang.String, java.util.UUID, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Short, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp, com.quizzes.api.common.model.jooq.enums.ContentProvider> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.util.UUID, java.lang.String, java.util.UUID, java.lang.Boolean, java.util.UUID, java.lang.String, java.lang.Short, java.lang.Boolean, java.sql.Timestamp, java.sql.Timestamp, com.quizzes.api.common.model.jooq.enums.ContentProvider> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.EXTERNAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.COLLECTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.IS_RESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field5() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.OWNER_PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.RESOURCE_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field7() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.SEQUENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.IS_DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.quizzes.api.common.model.jooq.enums.ContentProvider> field11() {
		return com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE.CONTENT_PROVIDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getExternalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getCollectionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getIsResource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value5() {
		return getOwnerProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getResourceData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value7() {
		return getSequence();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getIsDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.model.jooq.enums.ContentProvider value11() {
		return getContentProvider();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value2(java.lang.String value) {
		setExternalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value3(java.util.UUID value) {
		setCollectionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value4(java.lang.Boolean value) {
		setIsResource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value5(java.util.UUID value) {
		setOwnerProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value6(java.lang.String value) {
		setResourceData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value7(java.lang.Short value) {
		setSequence(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value8(java.lang.Boolean value) {
		setIsDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value9(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value10(java.sql.Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value11(com.quizzes.api.common.model.jooq.enums.ContentProvider value) {
		setContentProvider(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord values(java.util.UUID value1, java.lang.String value2, java.util.UUID value3, java.lang.Boolean value4, java.util.UUID value5, java.lang.String value6, java.lang.Short value7, java.lang.Boolean value8, java.sql.Timestamp value9, java.sql.Timestamp value10, com.quizzes.api.common.model.jooq.enums.ContentProvider value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ResourceRecord
	 */
	public ResourceRecord() {
		super(com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE);
	}

	/**
	 * Create a detached, initialised ResourceRecord
	 */
	public ResourceRecord(java.util.UUID id, java.lang.String externalId, java.util.UUID collectionId, java.lang.Boolean isResource, java.util.UUID ownerProfileId, java.lang.String resourceData, java.lang.Short sequence, java.lang.Boolean isDeleted, java.sql.Timestamp createdAt, java.sql.Timestamp updatedAt, com.quizzes.api.common.model.jooq.enums.ContentProvider contentProvider) {
		super(com.quizzes.api.common.model.jooq.tables.Resource.RESOURCE);

		setValue(0, id);
		setValue(1, externalId);
		setValue(2, collectionId);
		setValue(3, isResource);
		setValue(4, ownerProfileId);
		setValue(5, resourceData);
		setValue(6, sequence);
		setValue(7, isDeleted);
		setValue(8, createdAt);
		setValue(9, updatedAt);
		setValue(10, contentProvider);
	}
}
