/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Client implements java.io.Serializable {

	private static final long serialVersionUID = 1345479966;

	private java.util.UUID     id;
	private java.lang.String   name;
	private java.lang.String   description;
	private java.lang.Boolean  isActive;
	private java.util.UUID     apiKey;
	private byte[]             apiSecret;
	private java.sql.Timestamp createdAt;
	private java.sql.Timestamp updatedAt;

	public Client() {}

	public Client(
		java.util.UUID     id,
		java.lang.String   name,
		java.lang.String   description,
		java.lang.Boolean  isActive,
		java.util.UUID     apiKey,
		byte[]             apiSecret,
		java.sql.Timestamp createdAt,
		java.sql.Timestamp updatedAt
	) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.isActive = isActive;
		this.apiKey = apiKey;
		this.apiSecret = apiSecret;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(java.lang.Boolean isActive) {
		this.isActive = isActive;
	}

	public java.util.UUID getApiKey() {
		return this.apiKey;
	}

	public void setApiKey(java.util.UUID apiKey) {
		this.apiKey = apiKey;
	}

	public byte[] getApiSecret() {
		return this.apiSecret;
	}

	public void setApiSecret(byte[] apiSecret) {
		this.apiSecret = apiSecret;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public java.sql.Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(java.sql.Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}
}
