/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextProfile implements java.io.Serializable {

	private static final long serialVersionUID = 997440807;

	private java.util.UUID     id;
	private java.util.UUID     contextId;
	private java.util.UUID     profileId;
	private java.util.UUID     currentResourceId;
	private java.lang.Boolean  isComplete;
	private java.lang.String   eventSummaryData;
	private java.sql.Timestamp createdAt;
	private java.sql.Timestamp updatedAt;
	private java.lang.String   taxonomySummaryData;
	private java.lang.String   contextProfileData;

	public ContextProfile() {}

	public ContextProfile(
		java.util.UUID     id,
		java.util.UUID     contextId,
		java.util.UUID     profileId,
		java.util.UUID     currentResourceId,
		java.lang.Boolean  isComplete,
		java.lang.String   eventSummaryData,
		java.sql.Timestamp createdAt,
		java.sql.Timestamp updatedAt,
		java.lang.String   taxonomySummaryData,
		java.lang.String   contextProfileData
	) {
		this.id = id;
		this.contextId = contextId;
		this.profileId = profileId;
		this.currentResourceId = currentResourceId;
		this.isComplete = isComplete;
		this.eventSummaryData = eventSummaryData;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.taxonomySummaryData = taxonomySummaryData;
		this.contextProfileData = contextProfileData;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getContextId() {
		return this.contextId;
	}

	public void setContextId(java.util.UUID contextId) {
		this.contextId = contextId;
	}

	public java.util.UUID getProfileId() {
		return this.profileId;
	}

	public void setProfileId(java.util.UUID profileId) {
		this.profileId = profileId;
	}

	public java.util.UUID getCurrentResourceId() {
		return this.currentResourceId;
	}

	public void setCurrentResourceId(java.util.UUID currentResourceId) {
		this.currentResourceId = currentResourceId;
	}

	public java.lang.Boolean getIsComplete() {
		return this.isComplete;
	}

	public void setIsComplete(java.lang.Boolean isComplete) {
		this.isComplete = isComplete;
	}

	public java.lang.String getEventSummaryData() {
		return this.eventSummaryData;
	}

	public void setEventSummaryData(java.lang.String eventSummaryData) {
		this.eventSummaryData = eventSummaryData;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public java.sql.Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(java.sql.Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public java.lang.String getTaxonomySummaryData() {
		return this.taxonomySummaryData;
	}

	public void setTaxonomySummaryData(java.lang.String taxonomySummaryData) {
		this.taxonomySummaryData = taxonomySummaryData;
	}

	public java.lang.String getContextProfileData() {
		return this.contextProfileData;
	}

	public void setContextProfileData(java.lang.String contextProfileData) {
		this.contextProfileData = contextProfileData;
	}
}
