/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContextProfileEvent implements java.io.Serializable {

	private static final long serialVersionUID = 1239300335;

	private java.util.UUID     id;
	private java.util.UUID     contextProfileId;
	private java.util.UUID     resourceId;
	private java.lang.String   eventData;
	private java.sql.Timestamp createdAt;

	public ContextProfileEvent() {}

	public ContextProfileEvent(
		java.util.UUID     id,
		java.util.UUID     contextProfileId,
		java.util.UUID     resourceId,
		java.lang.String   eventData,
		java.sql.Timestamp createdAt
	) {
		this.id = id;
		this.contextProfileId = contextProfileId;
		this.resourceId = resourceId;
		this.eventData = eventData;
		this.createdAt = createdAt;
	}

	public java.util.UUID getId() {
		return this.id;
	}

	public void setId(java.util.UUID id) {
		this.id = id;
	}

	public java.util.UUID getContextProfileId() {
		return this.contextProfileId;
	}

	public void setContextProfileId(java.util.UUID contextProfileId) {
		this.contextProfileId = contextProfileId;
	}

	public java.util.UUID getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(java.util.UUID resourceId) {
		this.resourceId = resourceId;
	}

	public java.lang.String getEventData() {
		return this.eventData;
	}

	public void setEventData(java.lang.String eventData) {
		this.eventData = eventData;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
