/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.core.model.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrentContextProfile implements java.io.Serializable {

	private static final long serialVersionUID = 1263284452;

	private java.util.UUID     contextId;
	private java.util.UUID     profileId;
	private java.util.UUID     contextProfileId;
	private java.sql.Timestamp createdAt;

	public CurrentContextProfile() {}

	public CurrentContextProfile(
		java.util.UUID     contextId,
		java.util.UUID     profileId,
		java.util.UUID     contextProfileId,
		java.sql.Timestamp createdAt
	) {
		this.contextId = contextId;
		this.profileId = profileId;
		this.contextProfileId = contextProfileId;
		this.createdAt = createdAt;
	}

	public java.util.UUID getContextId() {
		return this.contextId;
	}

	public void setContextId(java.util.UUID contextId) {
		this.contextId = contextId;
	}

	public java.util.UUID getProfileId() {
		return this.profileId;
	}

	public void setProfileId(java.util.UUID profileId) {
		this.profileId = profileId;
	}

	public java.util.UUID getContextProfileId() {
		return this.contextProfileId;
	}

	public void setContextProfileId(java.util.UUID contextProfileId) {
		this.contextProfileId = contextProfileId;
	}

	public java.sql.Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.sql.Timestamp createdAt) {
		this.createdAt = createdAt;
	}
}
