/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionOnAir extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1921498955;

	/**
	 * The singleton instance of <code>public.collection_on_air</code>
	 */
	public static final com.quizzes.api.common.tables.CollectionOnAir COLLECTION_ON_AIR = new com.quizzes.api.common.tables.CollectionOnAir();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>public.collection_on_air.id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.collection_on_air.class_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.collection_on_air.collection_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COLLECTION_ID = createField("collection_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.collection_on_air</code> table reference
	 */
	public CollectionOnAir() {
		this("collection_on_air", null);
	}

	/**
	 * Create an aliased <code>public.collection_on_air</code> table reference
	 */
	public CollectionOnAir(java.lang.String alias) {
		this(alias, com.quizzes.api.common.tables.CollectionOnAir.COLLECTION_ON_AIR);
	}

	private CollectionOnAir(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased) {
		this(alias, aliased, null);
	}

	private CollectionOnAir(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.tables.CollectionOnAir as(java.lang.String alias) {
		return new com.quizzes.api.common.tables.CollectionOnAir(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.tables.CollectionOnAir rename(java.lang.String name) {
		return new com.quizzes.api.common.tables.CollectionOnAir(name, null);
	}
}
