/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collection extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 165922444;

	/**
	 * The singleton instance of <code>public.collection</code>
	 */
	public static final com.quizzes.api.common.tables.Collection COLLECTION = new com.quizzes.api.common.tables.Collection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>public.collection.id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.collection.external_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

	/**
	 * The column <code>public.collection.is_collection</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Boolean> IS_COLLECTION = createField("is_collection", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.collection.owner_profile_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> OWNER_PROFILE_ID = createField("owner_profile_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.collection.lms_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, com.quizzes.api.common.enums.Lms> LMS_ID = createField("lms_id", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.quizzes.api.common.enums.Lms.class), this, "");

	/**
	 * The column <code>public.collection.collection_body</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Object> COLLECTION_BODY = createField("collection_body", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>public.collection.is_deleted</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.collection.created_at</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.collection</code> table reference
	 */
	public Collection() {
		this("collection", null);
	}

	/**
	 * Create an aliased <code>public.collection</code> table reference
	 */
	public Collection(java.lang.String alias) {
		this(alias, com.quizzes.api.common.tables.Collection.COLLECTION);
	}

	private Collection(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased) {
		this(alias, aliased, null);
	}

	private Collection(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.tables.Collection as(java.lang.String alias) {
		return new com.quizzes.api.common.tables.Collection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.tables.Collection rename(java.lang.String name) {
		return new com.quizzes.api.common.tables.Collection(name, null);
	}
}
