/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Context extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -747691237;

	/**
	 * The singleton instance of <code>public.context</code>
	 */
	public static final com.quizzes.api.common.tables.Context CONTEXT = new com.quizzes.api.common.tables.Context();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>public.context.id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context.collection_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> COLLECTION_ID = createField("collection_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.context.context_body</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Object> CONTEXT_BODY = createField("context_body", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>public.context.created_at</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.context</code> table reference
	 */
	public Context() {
		this("context", null);
	}

	/**
	 * Create an aliased <code>public.context</code> table reference
	 */
	public Context(java.lang.String alias) {
		this(alias, com.quizzes.api.common.tables.Context.CONTEXT);
	}

	private Context(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased) {
		this(alias, aliased, null);
	}

	private Context(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.tables.Context as(java.lang.String alias) {
		return new com.quizzes.api.common.tables.Context(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.tables.Context rename(java.lang.String name) {
		return new com.quizzes.api.common.tables.Context(name, null);
	}
}
