/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventIndex extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 917379691;

	/**
	 * The singleton instance of <code>public.event_index</code>
	 */
	public static final com.quizzes.api.common.tables.EventIndex EVENT_INDEX = new com.quizzes.api.common.tables.EventIndex();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>public.event_index.id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.event_index.collection_unique_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COLLECTION_UNIQUE_ID = createField("collection_unique_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.event_index.is_complete</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Boolean> IS_COMPLETE = createField("is_complete", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>public.event_index.user_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.event_index</code> table reference
	 */
	public EventIndex() {
		this("event_index", null);
	}

	/**
	 * Create an aliased <code>public.event_index</code> table reference
	 */
	public EventIndex(java.lang.String alias) {
		this(alias, com.quizzes.api.common.tables.EventIndex.EVENT_INDEX);
	}

	private EventIndex(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased) {
		this(alias, aliased, null);
	}

	private EventIndex(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.tables.EventIndex as(java.lang.String alias) {
		return new com.quizzes.api.common.tables.EventIndex(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.tables.EventIndex rename(java.lang.String name) {
		return new com.quizzes.api.common.tables.EventIndex(name, null);
	}
}
