/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profile extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -549653271;

	/**
	 * The singleton instance of <code>public.profile</code>
	 */
	public static final com.quizzes.api.common.tables.Profile PROFILE = new com.quizzes.api.common.tables.Profile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>public.profile.id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.profile.external_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

	/**
	 * The column <code>public.profile.profile_body</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Object> PROFILE_BODY = createField("profile_body", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>public.profile.created_at</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.profile</code> table reference
	 */
	public Profile() {
		this("profile", null);
	}

	/**
	 * Create an aliased <code>public.profile</code> table reference
	 */
	public Profile(java.lang.String alias) {
		this(alias, com.quizzes.api.common.tables.Profile.PROFILE);
	}

	private Profile(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased) {
		this(alias, aliased, null);
	}

	private Profile(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.tables.Profile as(java.lang.String alias) {
		return new com.quizzes.api.common.tables.Profile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.tables.Profile rename(java.lang.String name) {
		return new com.quizzes.api.common.tables.Profile(name, null);
	}
}
