/**
 * This class is generated by jOOQ
 */
package com.quizzes.api.common.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Resource extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -665780627;

	/**
	 * The singleton instance of <code>public.resource</code>
	 */
	public static final com.quizzes.api.common.tables.Resource RESOURCE = new com.quizzes.api.common.tables.Resource();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>public.resource.id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.resource.external_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>public.resource.collection_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> COLLECTION_ID = createField("collection_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.resource.is_resource</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Boolean> IS_RESOURCE = createField("is_resource", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.resource.owner_profile_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.util.UUID> OWNER_PROFILE_ID = createField("owner_profile_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.resource.lms_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, com.quizzes.api.common.enums.Lms> LMS_ID = createField("lms_id", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.quizzes.api.common.enums.Lms.class), this, "");

	/**
	 * The column <code>public.resource.resource_body</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Object> RESOURCE_BODY = createField("resource_body", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>public.resource.is_deleted</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.resource.created_at</code>.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.resource</code> table reference
	 */
	public Resource() {
		this("resource", null);
	}

	/**
	 * Create an aliased <code>public.resource</code> table reference
	 */
	public Resource(java.lang.String alias) {
		this(alias, com.quizzes.api.common.tables.Resource.RESOURCE);
	}

	private Resource(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased) {
		this(alias, aliased, null);
	}

	private Resource(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.quizzes.api.common.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.quizzes.api.common.tables.Resource as(java.lang.String alias) {
		return new com.quizzes.api.common.tables.Resource(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.quizzes.api.common.tables.Resource rename(java.lang.String name) {
		return new com.quizzes.api.common.tables.Resource(name, null);
	}
}
